### ISSUE TITLE
[Feature]프로젝트_이슈 작성

### ISSUE THREAD

**Issue by Leegiyeon** [beyond-sw-camp/be04-2nd-if-1OR1-Tempository#15]
## 프로젝트_이슈 작성
----------------------------------
### 이슈 목적
> 프로젝트_이슈를 작성할 수 있다.

### 기능 구현 내용
- [x] 이슈 작성 기능
- [x] 서비스 테스트 코드 추가

### 참고사항
- VO(요청/응답), 서비스 PSA 구조 구현

**Comment by Leegiyeon** [comment]
해당 기능 구현 확인 되었습니다.

**Comment by onelee521** [comment]
테스트 코드 추가를 위해 이슈 리오픈 하였습니다.
