### ISSUE TITLE
[Feature]프로젝트_이슈 조회

### ISSUE THREAD

**Issue by Leegiyeon** [beyond-sw-camp/be04-2nd-if-1OR1-Tempository#5]
## 프로젝트_이슈 조회
----------------------------------
### 이슈 목적
> 프로젝트 단위 조회 및 이슈상태에 따른 조회

### 기능 구현 내용
- [x] 프로젝트ID로 이슈 조회
- [x] 이슈 상태에 따른 이슈 조회
- [x] 프로젝트 ID와 이슈 번호로 이슈 조회와 해당 이슈 담당자 정보 함께 조회(feign client 사용)
- [x] 테스트코드 추가

**Comment by Leegiyeon** [comment]
해당 기능 구현 확인하였습니다.

**Comment by onelee521** [comment]
테스트코드 추가를 위해 이슈 리오픈 하였습니다.
